const $ = (selector) => document.querySelector(selector);
const sections = [...document.querySelectorAll('.page-section')];
const navLinks = [...document.querySelectorAll('[data-section]')];
const labels = { inicio: 'Visão geral', biblia: 'Leitura bíblica', estudos: 'Estudos', identificar: 'Identificar versículo', perfil: 'Perfil' };
const translationPaths = { blivre: 'assets/bible', almeida1819: 'assets/bible/almeida1819' };
const defaultProgress = { xp: 0, level: 1, coins: 0, streak: 0, lastRead: '', completed: [], favorites: [] };
const state = { manifest: null, book: null, bookSlug: 'joao', chapter: 3, selectedVerse: 16, translation: 'blivre', fontSize: 22, progress: loadProgress(), cameraStream: null };

function loadProgress() { try { return { ...defaultProgress, ...JSON.parse(localStorage.getItem('verbo-web-progress') || '{}') }; } catch { return { ...defaultProgress }; } }
function saveProgress() { localStorage.setItem('verbo-web-progress', JSON.stringify(state.progress)); }
function keyForChapter() { return `${state.bookSlug}:${state.chapter}`; }
function keyForVerse() { return `${keyForChapter()}:${state.selectedVerse}`; }
function normalize(value) { return value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim(); }
function today() { return new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Sao_Paulo' }).format(new Date()); }
function yesterday() { const date = new Date(); date.setDate(date.getDate() - 1); return new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Sao_Paulo' }).format(date); }
function openSection(id) { sections.forEach((section) => section.classList.toggle('active', section.id === id)); navLinks.forEach((link) => link.classList.toggle('active', link.dataset.section === id)); $('#page-label').textContent = labels[id] || 'Verbo'; $('.sidebar').classList.remove('open'); if (id !== 'identificar') stopCamera(); }
navLinks.forEach((link) => link.addEventListener('click', () => openSection(link.dataset.section)));
document.querySelectorAll('a[href^="#"]').forEach((link) => link.addEventListener('click', () => { const id = link.getAttribute('href').slice(1); if (document.getElementById(id)) openSection(id); }));

async function fetchJson(path) { const response = await fetch(path); if (!response.ok) throw new Error(`Não foi possível carregar ${path}`); return response.json(); }
async function loadManifest() { state.manifest = await fetchJson(`${translationPaths[state.translation]}/manifest.json`); renderBookResults(); }
async function loadBook() { $('#scripture').innerHTML = '<p class="loading">Carregando as Escrituras…</p>'; state.book = await fetchJson(`${translationPaths[state.translation]}/${state.bookSlug}.json`); if (state.chapter > state.book.chapters.length) state.chapter = 1; renderBible(); }
function renderBible() {
  if (!state.book || !state.manifest) return;
  const current = state.book.chapters[state.chapter - 1] || [];
  const verse = current.find((item) => item.number === state.selectedVerse) || current[0]; state.selectedVerse = verse?.number || 1;
  $('#testament-label').textContent = state.book.testament === 'old' ? 'ANTIGO TESTAMENTO · 39 LIVROS' : 'NOVO TESTAMENTO · 27 LIVROS';
  $('#book-picker-button').textContent = state.book.name; $('#chapter-picker-button').textContent = `${state.chapter}⌄`; $('#chapter-meta').textContent = `${current.length} versículos · ${state.manifest.translation}`;
  $('#aside-reference').textContent = `${state.book.name.toUpperCase()} ${state.chapter}`; $('#aside-title').textContent = `Versículo ${state.selectedVerse}`; $('#aside-description').textContent = verse ? verse.text : 'Nenhum versículo disponível.';
  $('#completion-title').textContent = `Concluir ${state.book.name} ${state.chapter}`;
  $('#scripture').style.fontSize = `${state.fontSize}px`; $('#scripture').innerHTML = current.map(({ number, text }) => `<p class="${number === state.selectedVerse ? 'selected' : ''}" data-verse="${number}"><sup>${number}</sup>${text}</p>`).join('');
  $('#scripture').querySelectorAll('[data-verse]').forEach((element) => element.addEventListener('click', () => { state.selectedVerse = Number(element.dataset.verse); renderBible(); }));
  $('#favorite-verse').textContent = state.progress.favorites.includes(keyForVerse()) ? '♥ Remover favorito' : '♡ Favoritar';
  const complete = state.progress.completed.includes(keyForChapter()); const completeButton = $('#complete-chapter'); completeButton.disabled = complete; completeButton.innerHTML = complete ? '✓ Capítulo concluído <small>Recompensa conquistada</small>' : '✓ Marcar como lido <small>+40 XP · +8 ◆</small>'; updateDashboard();
}
function updateDashboard() {
  const { xp, level, coins, streak, completed } = state.progress; $('#level-count').textContent = level; $('#avatar-level').textContent = level; $('#coin-count').textContent = coins; $('#journey-level').textContent = `NÍVEL ${level}`; $('#streak-count').textContent = streak;
  $('#completed-label').textContent = completed.length ? `${completed.length} capítulo${completed.length > 1 ? 's' : ''} concluído${completed.length > 1 ? 's' : ''}. Continue a jornada!` : 'Conclua seu primeiro capítulo hoje.';
  $('#xp-progress').style.width = `${xp % 200 / 2}%`; $('#xp-label').textContent = `${xp % 200} / 200 XP para o próximo nível`; $('#current-reading').textContent = `${state.book?.name || 'João'} ${state.chapter}`;
  const verse = state.book?.chapters[state.chapter - 1]?.find((item) => item.number === state.selectedVerse); $('#current-verse').textContent = verse ? `“${verse.text.slice(0, 125)}${verse.text.length > 125 ? '…' : ''}”` : 'Leia a Palavra hoje.';
  $('#journey-total').textContent = `${completed.length} / 1.189`;
  const quests = [{ name: 'Gênesis', icon: '✦', threshold: 0 }, { name: 'Êxodo', icon: '♜', threshold: 5 }, { name: 'Salmos', icon: '☼', threshold: 10 }, { name: 'João', icon: '◆', threshold: 25 }, { name: 'Romanos', icon: '♛', threshold: 50 }];
  $('#quest-track').innerHTML = quests.map((quest, index) => { const done = completed.length >= (index + 1) * 5; const current = !done && completed.length >= quest.threshold; return `<article class="quest-node ${done ? 'done' : current ? 'current' : ''}"><i>${done ? '✓' : quest.icon}</i><b>${quest.name}</b><small>${done ? 'CONCLUÍDO' : current ? 'PRÓXIMA MISSÃO' : 'BLOQUEADO'}</small></article>`; }).join('');
  $('#profile-level').textContent = level; $('#profile-level-text').textContent = level; $('#profile-xp').textContent = `${xp} XP acumulados`; $('#favorite-count').textContent = state.progress.favorites.length; $('#completed-count').textContent = completed.length;
  const achievements = [{ icon: '✦', name: 'Primeiro passo', unlocked: completed.length >= 1 }, { icon: '🔥', name: 'Leitor fiel', unlocked: completed.length >= 5 }, { icon: '♜', name: 'Guardião', unlocked: completed.length >= 10 }];
  $('#achievement-list').innerHTML = achievements.map((item) => `<article class="${item.unlocked ? 'earned' : ''}"><i>${item.icon}</i><b>${item.name}</b></article>`).join('');
}
function moveChapter(direction) { if (!state.book || !state.manifest) return; const nextChapter = state.chapter + direction; if (nextChapter >= 1 && nextChapter <= state.book.chapters.length) { state.chapter = nextChapter; state.selectedVerse = 1; loadBook(); return; } const index = state.manifest.books.findIndex((book) => book.slug === state.bookSlug); const nextBook = state.manifest.books[index + direction]; if (nextBook) { state.bookSlug = nextBook.slug; state.chapter = direction > 0 ? 1 : nextBook.chapterCount; state.selectedVerse = 1; loadBook(); } }
function chooseBook(slug, chapter = 1) { state.bookSlug = slug; state.chapter = chapter; state.selectedVerse = 1; $('#book-dialog').close(); openSection('biblia'); loadBook(); }
function completeChapter() {
  const chapterKey = keyForChapter(); if (state.progress.completed.includes(chapterKey)) return; const firstReadToday = state.progress.lastRead !== today(); const xpGain = firstReadToday ? 60 : 40; const coinGain = firstReadToday ? 13 : 8;
  state.progress.streak = firstReadToday ? (state.progress.lastRead === yesterday() ? state.progress.streak + 1 : 1) : state.progress.streak; state.progress.lastRead = today(); state.progress.xp += xpGain; state.progress.coins += coinGain; state.progress.level = Math.floor(state.progress.xp / 200) + 1; state.progress.completed.push(chapterKey); saveProgress();
  $('#reward-xp').innerHTML = `+${xpGain}<small>XP</small>`; $('#reward-coins').innerHTML = `+${coinGain}<small>MOEDAS</small>`; $('#reward-dialog').showModal(); renderBible();
}
function toggleFavorite() { const reference = keyForVerse(); const index = state.progress.favorites.indexOf(reference); if (index >= 0) state.progress.favorites.splice(index, 1); else state.progress.favorites.push(reference); saveProgress(); renderBible(); }
async function copyVerse() { const verse = state.book?.chapters[state.chapter - 1]?.find((item) => item.number === state.selectedVerse); if (!verse) return; await navigator.clipboard?.writeText(`${state.book.name} ${state.chapter}:${verse.number} — ${verse.text}`); $('#copy-verse').textContent = '✓ Copiado'; setTimeout(() => { $('#copy-verse').textContent = '⧉ Copiar'; }, 1600); }
function renderBookResults(filter = '') { if (!state.manifest) return; const query = normalize(filter); const books = state.manifest.books.filter((book) => !query || normalize(`${book.name} ${book.abbreviation}`).includes(query)); $('#book-results').innerHTML = books.map((book) => `<button data-book="${book.slug}"><b>${book.name}</b><span>${book.chapterCount} capítulos · ${book.testament === 'old' ? 'AT' : 'NT'}</span></button>`).join(''); $('#book-results').querySelectorAll('[data-book]').forEach((button) => button.addEventListener('click', () => chooseBook(button.dataset.book))); }
function runSearch(value) {
  const query = normalize(value); const reference = query.match(/^(.+?)\s+(\d+)(?::(\d+))?$/); const books = (state.manifest?.books || []).filter((book) => query && (normalize(book.name) === query || normalize(book.abbreviation) === query || normalize(book.name).includes(query))).slice(0, 7); const referenceBook = reference && (state.manifest?.books || []).find((book) => normalize(book.name) === reference[1] || normalize(book.abbreviation) === reference[1]); const results = [];
  if (referenceBook && Number(reference[2]) <= referenceBook.chapterCount) results.push({ book: referenceBook, chapter: Number(reference[2]), label: `${referenceBook.name} ${reference[2]}${reference[3] ? `:${reference[3]}` : ''}` }); books.forEach((book) => { if (!results.some((item) => item.book.slug === book.slug)) results.push({ book, chapter: 1, label: book.name }); });
  $('#search-results').innerHTML = results.length ? results.map((item, index) => `<button data-result="${index}"><b>${item.label}</b><span>Abrir →</span></button>`).join('') : '<p class="search-hint">Nenhuma referência encontrada. Tente “Romanos 8” ou “Salmo 23”.</p>'; $('#search-results').querySelectorAll('[data-result]').forEach((button) => button.addEventListener('click', () => { const result = results[Number(button.dataset.result)]; chooseBook(result.book.slug, result.chapter); $('#search-dialog').close(); }));
}
async function startCamera() { try { state.cameraStream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'environment' } }); $('#camera-preview').srcObject = state.cameraStream; $('#scanner-empty').hidden = true; } catch { $('#scanner-empty').innerHTML = '<span>!</span><b>Câmera não disponível</b><p>Permita o acesso à câmera ou envie uma imagem para usar a demonstração.</p>'; } }
function stopCamera() { state.cameraStream?.getTracks().forEach((track) => track.stop()); state.cameraStream = null; }
function showScanResult() { const verse = state.book?.chapters[2]?.find((item) => item.number === 16); $('#scan-verse').textContent = verse ? `“${verse.text}”` : '“Porque Deus amou o mundo de tal maneira…”'; $('#scan-result').hidden = false; }

$('#menu-toggle').addEventListener('click', () => $('.sidebar').classList.toggle('open')); $('#theme-toggle').addEventListener('click', () => document.body.classList.toggle('dark')); $('#search-button').addEventListener('click', () => $('#search-dialog').showModal()); document.querySelectorAll('.dialog-close').forEach((button) => button.addEventListener('click', () => button.closest('dialog').close()));
document.addEventListener('keydown', (event) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); $('#search-dialog').showModal(); $('#reference').focus(); } }); $('#reference').addEventListener('input', (event) => runSearch(event.target.value)); $('#book-picker-button').addEventListener('click', () => { $('#book-dialog').showModal(); $('#book-filter').focus(); }); $('#chapter-picker-button').addEventListener('click', () => { $('#book-dialog').showModal(); $('#book-filter').focus(); }); $('#book-filter').addEventListener('input', (event) => renderBookResults(event.target.value));
$('#translation-select').addEventListener('change', async (event) => { state.translation = event.target.value; await loadManifest(); await loadBook(); }); $('#previous-chapter').addEventListener('click', () => moveChapter(-1)); $('#next-chapter').addEventListener('click', () => moveChapter(1)); $('#font-plus').addEventListener('click', () => { state.fontSize = Math.min(28, state.fontSize + 1); $('#scripture').style.fontSize = `${state.fontSize}px`; }); $('#font-minus').addEventListener('click', () => { state.fontSize = Math.max(17, state.fontSize - 1); $('#scripture').style.fontSize = `${state.fontSize}px`; }); $('#complete-chapter').addEventListener('click', completeChapter); $('#favorite-verse').addEventListener('click', toggleFavorite); $('#copy-verse').addEventListener('click', copyVerse); $('#start-camera').addEventListener('click', startCamera); $('#scan-demo').addEventListener('click', showScanResult); $('#image-upload').addEventListener('change', showScanResult); $('#open-scan-result').addEventListener('click', () => { stopCamera(); state.bookSlug = 'joao'; state.chapter = 3; state.selectedVerse = 16; openSection('biblia'); loadBook(); });
$('#open-favorites').addEventListener('click', () => { $('#search-dialog').showModal(); $('#search-results').innerHTML = state.progress.favorites.length ? state.progress.favorites.map((item) => `<button><b>${item.replaceAll(':', ' ')}</b><span>Favorito</span></button>`).join('') : '<p class="search-hint">Você ainda não salvou versículos.</p>'; });
Promise.resolve().then(loadManifest).then(loadBook).catch((error) => { $('#scripture').innerHTML = `<p class="loading">${error.message}</p>`; });
