export type CampaignRange = { slug: string; from: number; to: number };
export type CampaignMission = CampaignRange & { title: string };
export type CampaignAct = { number: number; title: string; ranges: CampaignRange[]; missions: CampaignMission[] };
export type MissionNarrative = { introduction: string; reflection: string; discovery: string; next: string };

const range = (slug: string, from: number, to: number): CampaignRange => ({ slug, from, to });
const mission = (slug: string, from: number, to: number, title: string): CampaignMission => ({ slug, from, to, title });

export const dailyReferences = [
  { slug: "joao", chapter: 3, verse: 16 },
  { slug: "sal", chapter: 23, verse: 1 },
  { slug: "rom", chapter: 8, verse: 28 },
  { slug: "fil", chapter: 4, verse: 13 },
  { slug: "isa", chapter: 41, verse: 10 },
] as const;

export const campaignActs: CampaignAct[] = [
  {
    number: 1,
    title: "O Princípio da Promessa",
    ranges: [range("gen", 1, 11)],
    missions: [mission("gen", 1, 1, "A Luz sobre o Abismo"), mission("gen", 2, 3, "O Jardim e a Escolha"), mission("gen", 4, 5, "A Terra Ferida"), mission("gen", 6, 9, "As Águas da Memória"), mission("gen", 10, 11, "A Torre dos Homens")],
  },
  {
    number: 2,
    title: "A Família da Aliança",
    ranges: [range("gen", 12, 50)],
    missions: [mission("gen", 12, 23, "O Chamado de Abraão"), mission("gen", 24, 36, "A Promessa entre Gerações"), mission("gen", 37, 50, "José e o Recomeço")],
  },
  {
    number: 3,
    title: "O Caminho da Libertação",
    ranges: [range("exod", 1, 40), range("lev", 1, 27), range("num", 1, 36), range("deut", 1, 34)],
    missions: [mission("exod", 1, 15, "A Noite da Partida"), mission("exod", 16, 40, "A Montanha da Aliança"), mission("lev", 1, 27, "Um Povo Separado"), mission("num", 1, 36, "O Deserto da Incredulidade"), mission("deut", 1, 34, "As Palavras de Moisés")],
  },
  {
    number: 4,
    title: "Terra, Reino e Ruína",
    ranges: [range("jos", 1, 24), range("juiz", 1, 21), range("rute", 1, 4), range("1sa", 1, 31), range("2sa", 1, 24), range("1rs", 1, 22), range("2rs", 1, 25), range("1crn", 1, 29), range("2crn", 1, 36), range("esd", 1, 10), range("nee", 1, 13), range("est", 1, 10)],
    missions: [mission("jos", 1, 24, "A Terra à Vista"), mission("juiz", 1, 21, "O Ciclo dos Juízes"), mission("rute", 1, 4, "Uma Estrangeira na Linhagem"), mission("1sa", 1, 31, "O Reino Escolhido"), mission("2sa", 1, 24, "A Casa de Davi"), mission("1rs", 1, 22, "O Reino Dividido"), mission("2rs", 1, 25, "A Queda e o Exílio"), mission("1crn", 1, 29, "Memória dos Reis"), mission("2crn", 1, 36, "A Ruína de Jerusalém"), mission("esd", 1, 10, "O Retorno"), mission("nee", 1, 13, "Muros Reconstruídos"), mission("est", 1, 10, "Providência no Exílio")],
  },
  {
    number: 5,
    title: "O Silêncio e a Esperança",
    ranges: [range("jo", 1, 42), range("sal", 1, 150), range("prov", 1, 31), range("ecl", 1, 12), range("cant", 1, 8), range("isa", 1, 66), range("jer", 1, 52), range("lam", 1, 5), range("eze", 1, 48), range("dan", 1, 12), range("ose", 1, 14), range("joel", 1, 3), range("amos", 1, 9), range("oba", 1, 1), range("jon", 1, 4), range("miq", 1, 7), range("naum", 1, 3), range("hab", 1, 3), range("sof", 1, 3), range("ageu", 1, 2), range("zac", 1, 14), range("mal", 1, 4)],
    missions: [mission("jo", 1, 42, "Quando o Justo Sofre"), mission("sal", 1, 150, "Cânticos no Escuro"), mission("prov", 1, 31, "O Peso da Sabedoria"), mission("ecl", 1, 12, "Sob o Sol e diante de Deus"), mission("cant", 1, 8, "Amor, Aliança e Fidelidade"), mission("isa", 1, 66, "A Voz do Profeta"), mission("jer", 1, 52, "A Palavra em Tempos de Ruína"), mission("lam", 1, 5, "Lágrimas sobre Sião"), mission("eze", 1, 48, "A Glória que Não Abandona"), mission("dan", 1, 12, "Fidelidade em Terra Estranha"), mission("ose", 1, 14, "Amor que Busca os Infieis"), mission("joel", 1, 3, "O Dia do Senhor"), mission("amos", 1, 9, "Justiça diante do Deus Santo"), mission("oba", 1, 1, "O Orgulho das Nações"), mission("jon", 1, 4, "Misericórdia além das Fronteiras"), mission("miq", 1, 7, "Juízo e Esperança"), mission("naum", 1, 3, "O Juiz das Nações"), mission("hab", 1, 3, "Viver pela Fé"), mission("sof", 1, 3, "O Dia e o Canto"), mission("ageu", 1, 2, "Reconstruir para a Glória"), mission("zac", 1, 14, "O Rei Humilde e Vitorioso"), mission("mal", 1, 4, "O Último Mensageiro")],
  },
  {
    number: 6,
    title: "O Verbo entre Nós",
    ranges: [range("mat", 1, 28), range("mar", 1, 16), range("luc", 1, 24), range("joao", 1, 21)],
    missions: [mission("mat", 1, 28, "O Rei Prometido"), mission("mar", 1, 16, "O Servo no Caminho"), mission("luc", 1, 24, "O Rosto dos Perdidos"), mission("joao", 1, 21, "O Verbo da Vida")],
  },
  {
    number: 7,
    title: "Até os Confins",
    ranges: [range("atos", 1, 28), range("rom", 1, 16), range("1cor", 1, 16), range("2cor", 1, 13), range("gal", 1, 6), range("efes", 1, 6), range("fil", 1, 4), range("col", 1, 4), range("1tes", 1, 5), range("2tes", 1, 3), range("1tim", 1, 6), range("2tim", 1, 4), range("tito", 1, 3), range("flm", 1, 1), range("heb", 1, 13), range("tiag", 1, 5), range("1ped", 1, 5), range("2ped", 1, 3), range("1joao", 1, 5), range("2joao", 1, 1), range("3joao", 1, 1), range("jud", 1, 1), range("apo", 1, 22)],
    missions: [mission("atos", 1, 28, "O Espírito e a Estrada"), mission("rom", 1, 16, "Uma Justiça que Alcança Todos"), mission("1cor", 1, 16, "Uma Comunidade em Construção"), mission("2cor", 1, 13, "Poder Aperfeiçoado na Fraqueza"), mission("gal", 1, 6, "A Liberdade da Graça"), mission("efes", 1, 6, "Uma Nova Humanidade"), mission("fil", 1, 4, "Alegria em Cristo"), mission("col", 1, 4, "A Supremacia de Cristo"), mission("1tes", 1, 5, "Esperança que Trabalha"), mission("2tes", 1, 3, "Firmes até o Fim"), mission("1tim", 1, 6, "Guardar o Bom Depósito"), mission("2tim", 1, 4, "A Fé Transmitida"), mission("tito", 1, 3, "A Graça que Forma um Povo"), mission("flm", 1, 1, "Um Irmão Recebido"), mission("heb", 1, 13, "Uma Esperança Melhor"), mission("tiag", 1, 5, "Fé que se Torna Visível"), mission("1ped", 1, 5, "Peregrinos na Esperança"), mission("2ped", 1, 3, "Crescer no Conhecimento"), mission("1joao", 1, 5, "Andar na Luz"), mission("2joao", 1, 1, "Verdade e Amor"), mission("3joao", 1, 1, "Servir a Verdade"), mission("jud", 1, 1, "Contender pela Fé"), mission("apo", 1, 22, "A Nova Criação")],
  },
];

export function missionForChapter(slug: string, chapter: number) {
  for (const act of campaignActs) {
    const found = act.missions.find((item) => item.slug === slug && chapter >= item.from && chapter <= item.to);
    if (found) return { act, mission: found };
  }
  return null;
}

const narrative = (introduction: string, reflection: string, discovery: string, next: string): MissionNarrative => ({ introduction, reflection, discovery, next });

const narratives: Record<string, MissionNarrative> = {
  // Ato I — criação, queda e a necessidade da promessa.
  "gen:1-1": narrative("Antes de cidades, reis e povos, a história começa com o Deus soberano criando pela sua palavra. Tudo depende dele e recebe dele sua bondade e propósito.", "O que o texto revela sobre o Criador antes de revelar algo sobre você?", "A primeira peça está no lugar: o mundo não é fruto do acaso, mas da palavra boa e poderosa de Deus.", "Mas como a criatura viverá no mundo que recebeu? O jardim guarda essa pergunta."),
  "gen:2-3": narrative("No jardim, Deus estabelece comunhão, vocação e um limite santo. A escolha humana expõe que o pecado é, no fundo, desconfiança da palavra de Deus.", "Em que momento o texto contrasta a voz de Deus com a voz da serpente?", "A queda alcança a relação com Deus, com o próximo e com a própria criação; ninguém se cura por si mesmo.", "Fora do jardim, a ferida logo aparecerá entre irmãos."),
  "gen:4-5": narrative("Depois da queda, o pecado deixa de ser apenas uma decisão interior e invade a casa, o culto e a cidade. Ainda assim, Deus preserva uma linhagem e mantém sua história.", "Que responsabilidade Deus atribui a Caim diante de seu irmão?", "A violência mostra a profundidade da ruína humana, mas a fidelidade de Deus não foi vencida pela ruína.", "A terra se enche; em breve, o juízo e a preservação caminharão juntos."),
  "gen:6-9": narrative("Em meio à corrupção generalizada, Noé não é apresentado como herói autônomo, mas como alguém alcançado pelo favor de Deus. Juízo e aliança estruturam esta leitura.", "Quais sinais de juízo e de preservação o texto mantém lado a lado?", "Deus julga o mal com santidade e preserva sua promessa com fidelidade; sua aliança sustenta o futuro da criação.", "Depois das águas, a humanidade ainda tentará construir um nome para si."),
  "gen:10-11": narrative("Povos, línguas e uma torre revelam a ambição de uma humanidade que busca segurança e fama sem submissão ao Criador. Deus governa até a dispersão das nações.", "O que os construtores de Babel desejam para si mesmos?", "A dispersão encerra o primeiro ato e prepara o contraste: Deus chamará uma família, não para exaltar seu nome, mas para abençoar as nações.", "A próxima voz será dirigida a Abrão, e a promessa ganhará um caminho histórico."),

  // Ato II — a aliança conduzida pela graça e providência de Deus.
  "gen:12-23": narrative("Deus chama Abrão sem que ele tenha construído mérito para isso e promete bênção que alcançará as nações. A aliança avança apesar de fraquezas, medos e esperas humanas.", "O que Deus promete realizar e o que pede de Abrão em resposta?", "A história da promessa não repousa na capacidade do patriarca, mas na fidelidade daquele que chama e sustenta.", "A promessa seguirá pela próxima geração, onde escolhas familiares revelarão a mesma graça perseverante."),
  "gen:24-36": narrative("Isaac e Jacó vivem entre disputas, fugas e encontros decisivos. O Deus da aliança continua presente, corrigindo e guardando sua promessa em pessoas imperfeitas.", "Como Deus demonstra fidelidade quando as relações humanas se tornam confusas?", "A eleição graciosa não desculpa o pecado, mas mostra que o propósito de Deus não depende da habilidade dos seus servos.", "Uma nova crise familiar levará José para longe e abrirá um caminho inesperado de preservação."),
  "gen:37-50": narrative("A história de José olha de frente para inveja, injustiça e sofrimento. Sem negar a maldade humana, ela testemunha a providência de Deus conduzindo a família da promessa.", "Onde o texto mostra responsabilidade humana e, ao mesmo tempo, o governo de Deus?", "Deus transforma o mal que homens praticam em ocasião de preservação, sem chamar o mal de bem.", "A família chega ao Egito; ali, a promessa enfrentará uma longa noite antes da libertação."),

  // Ato III — redenção, lei e peregrinação.
  "exod:1-15": narrative("Israel sofre sob um império que parece absoluto, mas o Senhor se lembra de sua aliança. A libertação começa pela iniciativa de Deus e culmina na Páscoa e no mar.", "Como a Páscoa mostra que libertação exige substituição e livramento provido por Deus?", "O Senhor derrota os falsos poderes e faz para si um povo redimido; a salvação vem dele, não da força de Israel.", "Libertos do Egito, eles agora aprenderão a viver diante do Deus que os resgatou."),
  "exod:16-40": narrative("No deserto e no Sinai, Deus alimenta, instrui e habita no meio de seu povo. A lei não compra a redenção; ela orienta os que já foram libertos pela graça.", "Que ordem o texto apresenta entre ser resgatado e obedecer?", "A presença de Deus é dádiva santa: o povo precisa de mediação, perdão e uma vida moldada por sua aliança.", "A jornada continua com instruções que mostram como um povo separado deve se aproximar de seu Deus."),
  "lev:1-27": narrative("Levítico desacelera para mostrar que o Deus que habita no meio do povo é santo. Sacrifícios, sacerdócio e pureza revelam a seriedade do pecado e a necessidade de expiação.", "O que estas instruções ensinam sobre aproximar-se de Deus nos próprios termos?", "A santidade não é detalhe religioso: ela expõe nossa necessidade de um mediador e de purificação provida por Deus.", "O povo seguirá pelo deserto, onde a confiança no Senhor será repetidamente provada."),
  "num:1-36": narrative("Entre censos, marchas e rebeliões, Números mostra um povo resgatado que ainda luta para crer. A incredulidade tem consequências reais, mas Deus não abandona sua promessa.", "Como as queixas do povo revelam uma dificuldade em confiar no caráter de Deus?", "A peregrinação ensina que a aliança é sustentada pela fidelidade divina, não pela estabilidade espiritual do povo.", "Às portas da terra, Moisés falará novamente para uma nova geração."),
  "deut:1-34": narrative("Moisés relembra a história antes da entrada na terra: graça, mandamentos, advertências e promessa. O coração do povo precisa mais do que informação; precisa ser voltado ao Senhor.", "Por que recordar a redenção passada é essencial para a obediência presente?", "A palavra de Deus forma uma comunidade de aliança e aponta para a necessidade de uma renovação que o próprio Deus deve operar.", "Com a morte de Moisés, a promessa da terra aguarda um novo líder."),

  // Ato IV — terra, reino, exílio e retorno.
  "jos:1-24": narrative("A terra é recebida como cumprimento de promessa, não como conquista que Israel possa reivindicar como mérito. A fidelidade de Deus permanece o centro desta entrada.", "Que memorial o povo estabelece e por que ele precisa lembrar a ação do Senhor?", "Deus cumpre o que prometeu e chama seu povo a responder com fé e fidelidade de aliança.", "Sem liderança firme, a próxima geração revelará como é fácil esquecer o Deus que concedeu a terra."),
  "juiz:1-21": narrative("Juízes retrata um ciclo sombrio: esquecimento, idolatria, opressão e livramento. Os libertadores não são salvadores perfeitos; eles revelam a necessidade de um rei justo e fiel.", "Qual padrão se repete quando o povo abandona o Senhor?", "A desordem de Israel mostra que o pecado alcança tanto líderes quanto povo e que libertações temporárias não bastam.", "Em meio a esse tempo escuro, uma pequena história de lealdade preservará a linhagem da promessa."),
  "rute:1-4": narrative("Em dias de instabilidade, Rute mostra a providência de Deus em decisões comuns, fidelidade familiar e acolhimento de uma estrangeira. Nada aqui é pequeno demais para sua mão.", "Que traços de fidelidade e generosidade orientam as relações desta história?", "Deus preserva a linhagem real por meios discretos e inclui uma estrangeira no caminho de sua promessa.", "A expectativa por um rei agora ganha rosto na história de uma família."),
  "1sa:1-31": narrative("Israel pede um rei como as nações, mas Deus deixa claro que seu governo não é substituído por instituições humanas. Samuel, Saul e Davi expõem o contraste entre aparência e coração.", "O que a escolha de Saul ensina sobre avaliar líderes apenas pelo que é visível?", "O Senhor reina sobre seu povo e procura servos que o temam; nenhum líder humano pode ocupar seu lugar.", "Davi receberá o trono, mas a promessa real passará também por seus pecados e suas crises."),
  "2sa:1-24": narrative("Davi é estabelecido como rei e recebe uma promessa duradoura, mas sua casa é atravessada pelo pecado. O reino precisa de uma fidelidade que o melhor dos reis terrenos não consegue oferecer.", "Como a narrativa mantém juntas a promessa feita a Davi e as consequências de seus pecados?", "A aliança davídica alimenta esperança, enquanto a queda de Davi impede qualquer confiança simplista no rei humano.", "Com Salomão, a glória do reino crescerá e seus alicerces começarão a rachar."),
  "1rs:1-22": narrative("Salomão constrói o templo e recebe sabedoria, mas seu coração dividido conduz o reino à divisão. A presença de Deus não pode ser domesticada por riqueza, templo ou poder político.", "Que diferença existe entre possuir muitos recursos religiosos e permanecer fiel ao Senhor?", "A divisão do reino revela que idolatria é infidelidade de aliança e que Deus permanece livre para julgar reis e povos.", "Profetas se levantarão para confrontar uma nação cada vez mais distante."),
  "2rs:1-25": narrative("Reis e profetas ocupam o cenário enquanto Israel e Judá caminham para o exílio. A queda não é acidente político; ela é apresentada como juízo paciente e justo de Deus.", "Como os profetas chamam o povo a retornar antes que o juízo chegue?", "Deus é fiel à sua palavra tanto nas advertências quanto nas promessas; a ruína do reino não cancela seu plano redentor.", "As genealogias olharão para trás para reinterpretar essa história à luz da adoração e da promessa."),
  "1crn:1-29": narrative("Crônicas organiza memórias, genealogias e o reinado de Davi para lembrar um povo fragilizado de sua identidade pactual. O culto e a promessa davídica ocupam o centro.", "Por que lembrar a história do povo e preparar a adoração são tarefas espirituais?", "Deus preserva sua promessa e chama seu povo a ordenar a vida em torno de sua presença, não de nostalgia nacional.", "A história seguirá para o templo, os reis de Judá e a disciplina que virá."),
  "2crn:1-36": narrative("A história de Judá é contada a partir do templo, da palavra profética e da resposta dos reis. Renovação e queda se alternam até que o exílio confirme a seriedade da aliança.", "Que atitudes distinguem os momentos de reforma dos momentos de decadência?", "Deus disciplina seu povo, mas sua disciplina não é abandono: ela preserva espaço para arrependimento e retorno.", "Um decreto inesperado abrirá o caminho de volta para Jerusalém."),
  "esd:1-10": narrative("Depois do exílio, um remanescente retorna para reconstruir o altar, o templo e a vida em torno da Palavra. O retorno é real, mas também revela que a restauração ainda é incompleta.", "O que recebe prioridade quando o povo volta a Jerusalém?", "A graça restauradora devolve o povo à adoração e à Escritura, mostrando que reconstrução verdadeira começa diante de Deus.", "Os muros ainda estão em ruínas, e uma nova geração será chamada a servir."),
  "nee:1-13": narrative("Neemias une oração, trabalho, liderança e reforma para reconstruir Jerusalém. A cidade só é reerguida de modo saudável quando a Palavra de Deus volta a moldar o povo.", "Como oração e ação responsável aparecem juntas nesta missão?", "A restauração não se resume a paredes: Deus reúne um povo que ouve, confessa e renova sua aliança.", "Mesmo no exílio, outra história mostrará a providência de Deus agindo onde seu nome não é pronunciado."),
  "est:1-10": narrative("Ester se passa longe de Jerusalém e não oferece soluções fáceis, mas mostra que a providência de Deus alcança palácios, decisões e ameaças invisíveis. Seu povo não está esquecido.", "Que sinais de providência você percebe mesmo quando Deus não é mencionado explicitamente?", "O Senhor preserva seu povo por caminhos que nem sempre enxergamos, sem tornar irrelevantes a coragem e a responsabilidade humanas.", "Chegamos ao silêncio dos sábios e profetas, onde a espera pela promessa ganha novas vozes."),

  // Ato V — sabedoria, profecia, juízo e esperança messiânica.
  "jo:1-42": narrative("Jó recusa explicações rasas para o sofrimento. O livro conduz da dor honesta à contemplação do Deus sábio, santo e livre, cuja providência ultrapassa nosso alcance.", "Como Jó é convidado a responder quando não recebe todas as razões para seu sofrimento?", "A soberania de Deus não minimiza a dor; ela impede que o sofrimento tenha a palavra final sobre a realidade.", "Da aflição de um justo, seguiremos para cânticos que ensinam o povo a orar em todas as estações."),
  "sal:1-150": narrative("Os Salmos formam a escola de oração do povo de Deus: lamento, louvor, confissão, gratidão e esperança messiânica. Aqui, a fé aprende a falar de modo verdadeiro diante do Senhor.", "Que tipo de oração o salmo de hoje lhe ensina a fazer com honestidade?", "Deus recebe seu povo em adoração e lamento, e os salmos mantêm a esperança ligada ao seu Rei e à sua aliança.", "A sabedoria agora perguntará como viver bem no mundo que Deus governa."),
  "prov:1-31": narrative("Provérbios ensina a temer ao Senhor no cotidiano: palavras, trabalho, família, justiça e escolhas. Sabedoria não é autonomia moral, mas vida recebida sob o governo de Deus.", "Como o temor do Senhor muda a forma de pensar uma decisão concreta?", "A vida sábia começa com reverência, pois só o Criador conhece plenamente a ordem de seu mundo.", "Mas o que acontece quando, mesmo com sabedoria, a vida parece frustrante e breve?"),
  "ecl:1-12": narrative("Eclesiastes olha sem disfarce para a vaidade das conquistas, do prazer e do controle. Debaixo do sol, as criaturas encontram limite; diante de Deus, recebem um chamado à reverência.", "Que tentativa de controlar a vida o texto revela como insuficiente?", "A sabedoria bíblica não elimina o mistério, mas nos devolve humildemente ao Criador, Juiz e doador de cada boa dádiva.", "O próximo poema celebrará o amor criado por Deus e a beleza da fidelidade."),
  "cant:1-8": narrative("Cantares celebra o amor conjugal dentro da bondade da criação, com linguagem poética que pede leitura reverente e cuidadosa. O amor humano é dádiva, não objeto de consumo ou domínio.", "Como o poema apresenta reciprocidade, compromisso e alegria no amor?", "A criação de Deus inclui afeto e fidelidade, e toda dádiva deve ser recebida com gratidão e santidade.", "A voz dos profetas levará a história de volta ao pecado nacional, ao juízo e à esperança de redenção."),
  "isa:1-66": narrative("Isaías confronta a falsa segurança de Judá e abre uma visão grandiosa do Santo de Israel. Juízo, remanescente, Servo e nova criação se unem na esperança que Deus mesmo provê.", "Como a santidade de Deus redefine o pecado e a esperança do povo?", "A salvação é obra do Senhor: ele julga o mal, preserva um povo e promete um Servo que carregará a culpa de muitos.", "Jeremias falará quando a ameaça do exílio se tornar inevitável."),
  "jer:1-52": narrative("Jeremias ministra a um povo que confia em símbolos religiosos enquanto resiste à Palavra de Deus. Sua mensagem une lágrimas, advertência e a promessa de uma nova aliança.", "Que diferença o livro mostra entre religião exterior e coração renovado?", "Deus julga a infidelidade de seu povo, mas promete escrever sua lei no coração e perdoar o pecado por sua própria graça.", "Quando Jerusalém cair, as lágrimas do profeta darão voz a uma fé que ainda espera."),
  "lam:1-5": narrative("Lamentações não apressa a dor de Jerusalém. Ela confessa o pecado, chora a ruína e, no meio do luto, lembra que as misericórdias do Senhor não se esgotam.", "Como a oração do livro mantém juntos lamento verdadeiro e esperança em Deus?", "A fé reformada não nega a disciplina divina nem transforma a dor em espetáculo; ela se volta ao Deus misericordioso em meio às ruínas.", "No exílio, Ezequiel verá que a glória de Deus não está presa a uma cidade ou edifício."),
  "eze:1-48": narrative("Ezequiel vê a glória do Senhor, denuncia o pecado do povo e anuncia juízo, renovação e presença restaurada. Deus age por causa de seu nome santo e de sua aliança.", "O que o livro diz sobre a incapacidade do povo de restaurar a si mesmo?", "A promessa de coração novo e Espírito novo mostra que a renovação é iniciativa soberana de Deus, não mera reforma externa.", "Em uma corte estrangeira, Daniel testemunhará que o Reino de Deus não perde seu domínio."),
  "dan:1-12": narrative("Daniel vive sob impérios sucessivos sem confundir fidelidade a Deus com domínio político. As visões e narrativas afirmam que o Altíssimo governa reis, tempos e reinos.", "Como Daniel e seus amigos permanecem fiéis quando o poder ao redor exige lealdade absoluta?", "O reino de Deus não é ameaçado por impérios humanos; ele chama seu povo à perseverança humilde e à esperança final.", "Os profetas menores concentrarão essa mesma esperança em palavras breves e penetrantes."),
  "ose:1-14": narrative("A infidelidade de Israel é apresentada pela dor de uma aliança rompida. Oséias não suaviza o pecado, mas também anuncia o amor perseverante de Deus que chama seu povo de volta.", "Como o livro mostra que idolatria é mais do que um erro intelectual?", "A graça não torna o adultério espiritual aceitável; ela revela a profundidade do amor de Deus que disciplina e restaura.", "Joel ampliará o horizonte: o Dia do Senhor aproxima juízo e derramamento do Espírito."),
  "joel:1-3": narrative("Uma calamidade convoca Judá ao lamento e ao retorno. Joel mostra que o Dia do Senhor é sério, mas também aponta para misericórdia e para o Espírito derramado por Deus.", "Que tipo de retorno o texto pede: exterior ou de coração?", "O Senhor chama seu povo a rasgar o coração e promete agir com graça, preparando uma esperança que alcança todas as nações.", "Amós falará contra uma adoração que canta, mas não pratica justiça."),
  "amos:1-9": narrative("Amós confronta uma sociedade próspera que mistura culto com injustiça. O Deus da aliança não aceita liturgia que convive tranquilamente com opressão e falsa segurança.", "Como o cuidado com o próximo aparece como fruto inseparável da adoração?", "A santidade de Deus alcança mercados, tribunais e altares; graça verdadeira produz justiça, não indiferença moral.", "A soberba das nações agora será julgada em uma breve palavra contra Edom."),
  "oba:1-1": narrative("Obadias denuncia a arrogância de Edom, que celebrou a queda de seu irmão. Nenhuma segurança geográfica, militar ou política está fora do juízo do Senhor.", "Que formas de orgulho coletivo o texto expõe?", "Deus vê a violência que nações normalizam e mantém o direito de julgar toda arrogância humana.", "Jonas será enviado a outra nação inimiga e colocará a misericórdia de Deus no centro da crise."),
  "jon:1-4": narrative("Jonas conhece a misericórdia de Deus, mas resiste a vê-la alcançar Nínive. O livro confronta um coração religioso que prefere controlar a graça em vez de celebrar seu alcance.", "Por que a misericórdia de Deus se torna difícil para Jonas?", "O Senhor é livre e compassivo; sua graça alcança quem ele chama e expõe nossos limites estreitos para o seu reino.", "Miqueias reunirá denúncia social, esperança real e a promessa de um governante vindo de Belém."),
  "miq:1-7": narrative("Miqueias denuncia líderes e povo por injustiça e idolatria, mas também anuncia um pastor-rei e um Deus que se deleita em perdoar. Juízo e esperança não se anulam.", "O que o Senhor requer de seu povo segundo a mensagem do profeta?", "A esperança não vem da força de Jerusalém, mas do Deus que perdoa, restaura e levanta seu Rei prometido.", "Naum falará da queda de Nínive para lembrar que a paciência de Deus não é indiferença ao mal."),
  "naum:1-3": narrative("Naum anuncia a queda de Nínive, capital de um império violento. O livro preserva uma verdade necessária: o Deus paciente também é justo e não inocenta o culpado.", "Como o juízo de Deus serve de consolo aos que sofrem violência?", "A justiça divina impede que o poder brutal seja a realidade definitiva; Deus vê, julga e sustenta os que nele se refugiam.", "Habacuque levará a pergunta ainda mais perto: como viver quando o mal parece avançar?"),
  "hab:1-3": narrative("Habacuque conversa com Deus sem esconder sua perplexidade diante da violência e do uso da Babilônia como instrumento de juízo. A resposta chama o justo a viver pela fé.", "O que significa confiar em Deus quando suas respostas não seguem nosso calendário?", "A fé não é negar a crise; é descansar no caráter de Deus e perseverar sob sua palavra quando a visão parece demorar.", "Sofonias reunirá o anúncio do Dia do Senhor com a promessa de um povo humilde e restaurado."),
  "sof:1-3": narrative("Sofonias anuncia o Dia do Senhor contra o pecado de Judá e das nações, mas termina com a esperança de um remanescente purificado e de Deus no meio de seu povo.", "Que contraste há entre autossuficiência e humildade diante do Senhor?", "O juízo de Deus visa expor o mal e formar um povo que confia somente nele, não em sua própria força.", "Após o exílio, Ageu chamará o povo a ordenar novamente sua vida em torno da glória de Deus."),
  "ageu:1-2": narrative("O povo retornado enfrentava escassez e desânimo, enquanto a casa de Deus permanecia negligenciada. Ageu chama a reconsiderar prioridades à luz da presença e da glória do Senhor.", "O que o livro revela sobre colocar projetos pessoais acima da adoração a Deus?", "Deus não pede reconstrução para preencher uma carência sua; ele forma um povo cuja vida inteira reconhece sua glória.", "Zacarias abrirá visões de purificação, restauração e do Rei que vem humilde."),
  "zac:1-14": narrative("Zacarias fala a um povo pequeno e cansado com visões de perdão, templo, pastor e rei. A restauração presente aponta para uma obra maior que Deus realizará.", "Que imagens do livro mostram que Deus mesmo remove a culpa e sustenta seu povo?", "A esperança messiânica nasce da graça: o Senhor purifica, reúne e promete um Rei humilde que trará paz verdadeira.", "Malaquias encerrará o Antigo Testamento chamando o povo à fidelidade e à espera do mensageiro prometido."),
  "mal:1-4": narrative("Malaquias confronta uma religião cansada, marcada por culto negligente e infidelidade. Deus chama seu povo de volta ao temor de seu nome e à esperança de sua visitação.", "Onde a rotina religiosa pode esconder um coração que deixou de honrar a Deus?", "A promessa permanece viva: o Senhor virá para purificar seu povo e preparar o caminho para a redenção esperada.", "Depois de longa espera, os Evangelhos anunciarão que a promessa entrou na história em Jesus Cristo."),

  // Ato VI — a chegada, a obra e a revelação de Cristo.
  "mat:1-28": narrative("Mateus apresenta Jesus como o Filho de Davi e Filho de Abraão, o Rei prometido que cumpre as Escrituras. Seu reino confronta a justiça própria e chama discípulos a segui-lo.", "Como as promessas antigas encontram cumprimento na pessoa e na obra de Jesus?", "Em Cristo, a história da aliança chega ao seu centro: o Rei serve, morre, ressuscita e recebe toda autoridade.", "Marcos nos fará acompanhar esse mesmo Senhor pelo caminho do Servo sofredor."),
  "mar:1-16": narrative("Marcos move a narrativa com urgência e pergunta quem é Jesus. Poder, compaixão, confronto e cruz revelam que o Messias reina justamente ao entregar sua vida em resgate.", "Em que momentos os discípulos precisam reaprender o que significa seguir o Cristo?", "A cruz não é acidente nem derrota: nela o Filho do Homem cumpre sua missão de servir e dar a vida por muitos.", "Lucas abrirá as portas da história para os improváveis, feridos e esquecidos."),
  "luc:1-24": narrative("Lucas apresenta Jesus como o Salvador que busca os perdidos e cumpre o plano de Deus na história. Mulheres, pobres, pecadores e estrangeiros são vistos sob a luz de sua graça.", "Como Jesus redefine quem está próximo e quem precisa de misericórdia?", "A graça de Cristo não confirma nossa autossuficiência; ela chama pecadores ao arrependimento, à fé e a uma vida de gratidão.", "João nos levará ainda mais fundo na identidade do Filho eterno que veio revelar o Pai."),
  "joao:1-21": narrative("João organiza sinais e conversas para que vejamos Jesus como o Verbo eterno feito carne. Vida, luz, glória, cruz e ressurreição apontam para a fé nele.", "Que sinal ou declaração de Jesus mais claramente revela sua identidade neste trecho?", "Crer em Cristo é receber a vida que ele dá por graça; sua cruz manifesta simultaneamente amor, juízo e vitória.", "O Cristo ressuscitado enviará testemunhas, e a promessa do Espírito abrirá a história da igreja."),

  // Ato VII — igreja, evangelho, perseverança e nova criação.
  "atos:1-28": narrative("Atos mostra o Cristo ressuscitado continuando sua obra pelo Espírito, através de uma igreja frágil e testemunhal. O evangelho atravessa fronteiras sem depender de segurança política.", "Como o Espírito capacita a igreja a anunciar Cristo em meio a oposição e mudança?", "A missão nasce do senhorio de Jesus e avança pela Palavra, oração e poder do Espírito, não por controle humano.", "Paulo escreverá a Roma para explicar a justiça de Deus revelada no evangelho."),
  "rom:1-16": narrative("Romanos expõe a culpa universal do pecado e anuncia a justiça de Deus recebida pela fé em Cristo. Ele une justificação, união com Cristo, eleição, vida no Espírito e missão.", "Como o evangelho derruba tanto a culpa do rebelde quanto a vanglória do religioso?", "A salvação é do Senhor: pecadores são justificados por graça, em Cristo, mediante a fé, para que toda glória pertença a Deus.", "Em Corinto, essa mesma graça precisará formar uma comunidade dividida e imatura."),
  "1cor:1-16": narrative("Paulo trata uma igreja rica em dons, mas marcada por divisões, orgulho e desordem. A cruz de Cristo corrige toda tentativa de medir maturidade por prestígio ou poder.", "Onde a mensagem da cruz confronta a forma como a comunidade busca status?", "A igreja é corpo de Cristo e vive de sua graça; seus dons devem servir ao amor, à santidade e à edificação comum.", "A próxima carta mostrará um apóstolo fraco aos olhos do mundo, mas sustentado pelo poder de Deus."),
  "2cor:1-13": narrative("Em 2 Coríntios, Paulo abre o coração de um ministro ferido e consola uma igreja instável. Fraqueza, reconciliação, generosidade e ministério são interpretados pela suficiência da graça de Cristo.", "Como a fraqueza pode se tornar lugar de dependência, e não de desespero?", "O poder de Deus não confirma a autossuficiência; ele se aperfeiçoa em servos que reconhecem sua dependência de Cristo.", "Gálatas enfrentará uma ameaça direta a essa graça: acrescentar méritos humanos ao evangelho."),
  "gal:1-6": narrative("Gálatas defende a suficiência do evangelho contra qualquer retorno à justificação por obras da lei. Em Cristo, liberdade não é autonomia: é vida no Espírito e serviço em amor.", "O que se perde quando a aceitação diante de Deus depende do desempenho humano?", "A justificação é dom da graça em Cristo; por isso, a obediência é fruto de uma nova identidade, não moeda para comprar favor.", "Efésios ampliará essa visão e mostrará como Deus forma um só povo em Cristo."),
  "efes:1-6": narrative("Efésios contempla o propósito eterno de Deus de reunir todas as coisas em Cristo. Ele cria uma nova humanidade, reconcilia inimigos e sustenta sua igreja pela graça e pela Palavra.", "Como a união com Cristo muda a identidade pessoal e a vida em comunidade?", "A salvação é obra trinitária de Deus, recebida pela graça, e resulta em uma igreja que exibe sua reconciliação diante do mundo.", "Em uma prisão, Paulo mostrará que a alegria cristã não depende de circunstâncias favoráveis."),
  "fil:1-4": narrative("Filipenses é uma carta de alegria escrita em limitações reais. Paulo aponta para Cristo humilhado e exaltado, ensinando uma comunidade a perseverar com humildade e contentamento.", "De que forma o exemplo de Cristo redefine ambição e serviço?", "A alegria cristã está ancorada no Senhor e na comunhão com ele, não na estabilidade das circunstâncias ou no sucesso visível.", "Colossenses guardará essa alegria ao reafirmar a supremacia suficiente de Cristo contra toda alternativa."),
  "col:1-4": narrative("Colossenses anuncia que Cristo é supremo sobre criação, igreja e poderes espirituais. Nele habita toda a plenitude, e nele os crentes recebem uma identidade completa.", "Que alternativas ao evangelho parecem espirituais, mas diminuem a suficiência de Cristo?", "Nada precisa ser acrescentado a Cristo para tornar seu povo aceito diante de Deus; ele é Senhor suficiente e cabeça da igreja.", "A esperança da volta de Cristo agora fortalecerá uma igreja jovem em Tessalônica."),
  "1tes:1-5": narrative("Os tessalonicenses recebem o evangelho em meio à aflição e aprendem a esperar o Filho que virá dos céus. Fé, amor e esperança se tornam marcas visíveis de uma comunidade transformada.", "Como a esperança da volta de Cristo influencia o trabalho e a santidade no presente?", "A esperança cristã não é fuga do mundo: ela produz perseverança, amor fraternal e vida santa diante do Deus que chama.", "Dúvidas sobre o Dia do Senhor exigirão mais firmeza e discernimento na próxima carta."),
  "2tes:1-3": narrative("Paulo encoraja uma igreja pressionada e corrige confusões sobre o fim. A volta de Cristo é certa, mas a espera deve formar perseverança, sobriedade e trabalho fiel.", "Como a certeza do fim molda uma vida responsável no presente?", "A escatologia bíblica consola os aflitos e corrige a ociosidade: o povo de Deus espera ativamente, sustentado por sua fidelidade.", "As cartas pastorais voltarão o olhar para a vida ordenada e ensinável da igreja local."),
  "1tim:1-6": narrative("Primeira Timóteo trata da verdade do evangelho, oração, liderança e piedade numa igreja ameaçada por falsos ensinos. A casa de Deus deve refletir o caráter daquele que a salvou.", "Por que doutrina saudável e vida santa não podem ser separadas?", "A igreja guarda o evangelho como depósito recebido; líderes e membros servem sob a autoridade da Palavra, não de preferências pessoais.", "A última carta de Paulo a Timóteo chamará a perseverar quando a oposição se tornar mais pessoal."),
  "2tim:1-4": narrative("Em sua última carta, Paulo chama Timóteo a não se envergonhar do evangelho, a sofrer pelo nome de Cristo e a permanecer nas Escrituras inspiradas por Deus.", "Como a suficiência das Escrituras equipa a igreja para tempos difíceis?", "A fidelidade não depende de uma geração sem conflitos; Deus preserva seu povo por sua Palavra e convoca servos a transmiti-la com coragem.", "Tito mostrará como essa verdade ganha forma concreta em comunidades recém-organizadas."),
  "tito:1-3": narrative("Tito une liderança saudável, ensino sólido e boas obras. A graça que salva sem mérito também educa o povo de Deus a renunciar à impiedade e viver de modo útil.", "Como o texto relaciona a bondade salvadora de Deus com uma vida renovada?", "Boas obras não são a causa da salvação, mas seu fruto necessário numa comunidade alcançada pela misericórdia de Deus.", "Filemom mostrará essa graça operando numa relação pessoal marcada por desigualdade e reconciliação."),
  "flm:1-1": narrative("Filemom é breve, mas torna visível o poder do evangelho numa relação concreta. Paulo apela por Onésimo não como objeto de cálculo, mas como irmão amado em Cristo.", "Que mudança o evangelho exige na maneira de enxergar alguém socialmente inferior ou distante?", "A união com Cristo cria uma fraternidade real que confronta orgulho, utilidade e indiferença, sem reduzir a reconciliação a palavras.", "Hebreus levará os olhos da igreja para o mediador perfeito e a aliança superior."),
  "heb:1-13": narrative("Hebreus apresenta Jesus como o Filho superior, o grande Sumo Sacerdote e mediador da nova aliança. Diante da tentação de recuar, a igreja é chamada a aproximar-se de Deus por ele.", "Que aspecto da obra de Cristo torna possível perseverar com confiança?", "Cristo é suficiente para salvar e sustentar seu povo; sua mediação final substitui toda confiança em sombras, méritos ou retornos ao passado.", "Tiago mostrará como essa fé perseverante se torna visível em palavras, obras e sabedoria."),
  "tiag:1-5": narrative("Tiago fala a crentes dispersos e provados, chamando-os a uma fé íntegra. Ouvir a Palavra, dominar a língua, cuidar do próximo e resistir ao orgulho pertencem à mesma vida de fé.", "Que evidência concreta de fé o texto chama você a considerar?", "A fé que justifica nunca permanece estéril: ela produz frutos de obediência, misericórdia e humildade, não para merecer graça, mas porque foi alcançada por ela.", "Pedro escreverá a peregrinos que precisam dessa mesma esperança em meio ao sofrimento."),
  "1ped:1-5": narrative("Pedro se dirige a peregrinos que sofrem por pertencer a Cristo. Ele ancora a identidade da igreja na eleição, no novo nascimento e na esperança de uma herança guardada por Deus.", "Como a esperança futura sustenta santidade e mansidão no sofrimento presente?", "Deus guarda seu povo pela fé e o chama a testemunhar com humildade; sofrer por Cristo não é sinal de abandono do Pastor das almas.", "A segunda carta advertirá sobre vozes que distorcem a verdade e exploram a comunidade."),
  "2ped:1-3": narrative("Segunda Pedro chama a igreja a crescer no conhecimento de Cristo e a discernir falsos mestres. A demora percebida da promessa não é falha, mas expressão da paciência de Deus.", "Como o caráter e a promessa de Deus ajudam a avaliar ensinos atraentes?", "A perseverança exige doutrina firme e vida piedosa; o Senhor cumprirá sua palavra no tempo certo e julgará todo engano.", "João agora resumirá a vida cristã em luz, verdade, amor e comunhão com o Pai e o Filho."),
  "1joao:1-5": narrative("Primeira João oferece sinais pastorais de comunhão verdadeira: fé no Filho encarnado, caminhada na luz, amor aos irmãos e obediência. A certeza nasce de Cristo, não de desempenho isolado.", "Como o texto mantém unidos verdade sobre Jesus, amor e obediência?", "A segurança do crente repousa no Filho e em sua obra; os frutos de amor e fé confirmam uma vida que Deus gerou.", "A carta seguinte protegerá essa verdade em meio a mestres que negam o ensino apostólico."),
  "2joao:1-1": narrative("Segunda João fala de amor moldado pela verdade. Hospitalidade e generosidade precisam de discernimento, porque acolher ensino falso participa de sua obra destrutiva.", "Por que amor cristão não pode ser separado da verdade sobre Cristo?", "A igreja ama de modo fiel quando permanece na doutrina de Cristo; tolerância ao erro não é a mesma coisa que caridade.", "Terceira João mostrará como apoiar servos fiéis da verdade em uma comunidade real."),
  "3joao:1-1": narrative("Terceira João contrasta hospitalidade humilde com liderança que busca preeminência. A verdade avança quando a igreja recebe servos fiéis e rejeita ambição que fere a comunhão.", "Que tipo de liderança o texto aprova e qual ele reprova?", "Servir a verdade exige humildade e generosidade; ninguém deve ocupar na igreja o lugar de preeminência que pertence a Cristo.", "Judas chamará os crentes a proteger essa fé quando falsos mestres se infiltram no povo."),
  "jud:1-1": narrative("Judas convoca a igreja a batalhar pela fé confiada de uma vez por todas aos santos. A defesa da verdade é feita com temor, misericórdia e confiança no Deus que guarda.", "Como o texto equilibra firmeza contra o erro e misericórdia com os que vacilam?", "A igreja persevera porque Deus é poderoso para guardar seu povo, e por isso ela é chamada a permanecer, discernir e servir com amor.", "Apocalipse abrirá a cortina final: Cristo reina, a igreja sofre com esperança e Deus fará novas todas as coisas."),
  "apo:1-22": narrative("Apocalipse revela Jesus Cristo como Senhor ressuscitado, Juiz justo e Cordeiro vencedor. Com imagens apocalípticas, fortalece a igreja a adorar, perseverar e esperar a nova criação.", "Que visão de Cristo ajuda a enfrentar medo, sedução ou sofrimento no presente?", "A história termina onde a graça pretende levá-la: Deus habita com seu povo, o mal é julgado e o Cordeiro recebe toda a adoração.", "A jornada bíblica se conclui com esperança certa: Cristo reina e fará novas todas as coisas."),
};

export function narrativeForMission(mission: CampaignMission): MissionNarrative {
  const key = `${mission.slug}:${mission.from}-${mission.to}`;
  return narratives[key] ?? {
    introduction: `Nesta parte da Grande História, ${mission.title.toLowerCase()} conduz a leitura de ${mission.from === mission.to ? "um capítulo" : "uma nova sequência de capítulos"}. Observe o texto antes de tirar conclusões apressadas.`,
    reflection: "Que parte do texto ajuda você a compreender melhor o que veio antes?",
    discovery: "Cada leitura amplia a compreensão da história bíblica e do lugar deste trecho nela.",
    next: "A próxima etapa revelará uma nova consequência e uma nova pergunta para acompanhar.",
  };
}
